In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(28,400,5)

array([ 28,  33,  38,  43,  48,  53,  58,  63,  68,  73,  78,  83,  88,
        93,  98, 103, 108, 113, 118, 123, 128, 133, 138, 143, 148, 153,
       158, 163, 168, 173, 178, 183, 188, 193, 198, 203, 208, 213, 218,
       223, 228, 233, 238, 243, 248, 253, 258, 263, 268, 273, 278, 283,
       288, 293, 298, 303, 308, 313, 318, 323, 328, 333, 338, 343, 348,
       353, 358, 363, 368, 373, 378, 383, 388, 393, 398])

In [11]:
np.linspace(44,900,55)

array([ 44.        ,  59.85185185,  75.7037037 ,  91.55555556,
       107.40740741, 123.25925926, 139.11111111, 154.96296296,
       170.81481481, 186.66666667, 202.51851852, 218.37037037,
       234.22222222, 250.07407407, 265.92592593, 281.77777778,
       297.62962963, 313.48148148, 329.33333333, 345.18518519,
       361.03703704, 376.88888889, 392.74074074, 408.59259259,
       424.44444444, 440.2962963 , 456.14814815, 472.        ,
       487.85185185, 503.7037037 , 519.55555556, 535.40740741,
       551.25925926, 567.11111111, 582.96296296, 598.81481481,
       614.66666667, 630.51851852, 646.37037037, 662.22222222,
       678.07407407, 693.92592593, 709.77777778, 725.62962963,
       741.48148148, 757.33333333, 773.18518519, 789.03703704,
       804.88888889, 820.74074074, 836.59259259, 852.44444444,
       868.2962963 , 884.14814815, 900.        ])

In [16]:
a_array=np.array([[2,3,4],[5,6,7],[8,9,0]])

In [17]:
a_array.shape

(3, 3)

In [18]:
a_array.ndim

2

In [19]:
a_array.dtype

dtype('int64')

In [31]:
b_array=np.array([[90,91,92],[93,94,95],[96,97,99],[906,907,909]])

In [32]:
res=b_array.reshape(2,6)

In [33]:
res

array([[ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  99, 906, 907, 909]])

In [34]:
b_array.flatten()

array([ 90,  91,  92,  93,  94,  95,  96,  97,  99, 906, 907, 909])

In [35]:
np.sum(b_array,axis=1)

array([ 273,  282,  292, 2722])

In [36]:
b_array[2][2]

np.int64(99)

In [37]:
flat=b_array.flatten()

In [41]:
sliced=flat[2:5].copy()

In [42]:
sliced

array([92, 93, 94])

In [43]:
sliced[2]=43

In [44]:
sliced

array([92, 93, 43])

In [46]:
flat

array([ 90,  91,  92,  93,  94,  95,  96,  97,  99, 906, 907, 909])

In [10]:
np.bool(5<9)

np.True_